### ISSUE TITLE
Vulnerability: express-ipfilter use Depends on vulnerable versions of ip package

### ISSUE THREAD

**Issue by DmytroShalaiev** [jetersen/express-ipfilter#159]
ip  *
Severity: high
NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks - https://github.com/advisories/GHSA-78xj-cgh5-2h22
No fix available
node_modules/ip
  express-ipfilter  *
  Depends on vulnerable versions of ip
  node_modules/express-ipfilter
  
![Снимок экрана 2024-02-14 в 12 37 46](https://github.com/jetersen/express-ipfilter/assets/26797262/5292c003-1a1a-46b7-8142-aed43b38ccea)

**Comment by jetersen** [comment]
Not relevant, we do not use `isPublic`

**Comment by DmytroShalaiev** [comment]
Thanks for reply, I am about this package https://github.com/jetersen/express-ipfilter/blob/master/package.json#L78

**Comment by DmytroShalaiev** [comment]
But seems there is no fix from https://github.com/indutny/node-ip

**Comment by jetersen** [comment]
But the vulnerability is only in there if you actively use `isPublic`
Please read the CVE.

**Comment by DmytroShalaiev** [comment]
Oh, sure, I understood, thanks for the reply.

**Comment by odubuc** [comment]
This logic doesn't compute for me. 
what is the downside to upgrade and get rid of false positive report ?

**Comment by jetersen** [comment]
Feel free to submit a PR. There are plenty of false positive.

**Comment by jetersen** [comment]
Fixed in https://github.com/jetersen/express-ipfilter/releases/tag/v1.3.2

**Comment by odubuc** [comment]
Thanks will do next time. I misunderstood your comment
