### ISSUE TITLE
IPv4/IPv6 Namespace ::ffff:

### ISSUE THREAD

**Issue by rx2347** [jetersen/express-ipfilter#49]
For those who come accross this: express returns IP4 addresses with ::ffff: prefixes, so '127.0.0.1' from the examples won't match anything, while '::ffff:127.0.0.1' does.

Maybe add this as a customDetection example? 

```
const customDetection = (req) => {
  let ip = req.headers["x-forwarded-for"] || req.connection.remoteAddress;
  ip = ip.replace("::ffff:", "");

  return ip;
};

```

More information:
[https://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1](https://stackoverflow.com/questions/29411551/express-js-req-ip-is-returning-ffff127-0-0-1)

**Comment by jetersen** [comment]
Feel free to update the readme in a pull request!
