### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by aspic** [jetersen/express-ipfilter#72]
Hey!

It would be nice to get the logF typescript declaration at https://github.com/jetersen/express-ipfilter/commit/83c806c09883ef3d24919c73ecc955165db0b1d8 in a published version of this library!

**Comment by jetersen** [comment]
Done https://github.com/jetersen/express-ipfilter/releases/tag/v1.2.0 :)

**Comment by aspic** [comment]
Thanks! :D
